# Generated by Django 5.1.3 on 2025-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="try_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
