# Generated by Django 5.1.3 on 2025-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0002_customuser_try_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="verify_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
