# Generated by Django 5.1.3 on 2025-02-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0003_customuser_verify_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
