# Generated by Django 5.1.3 on 2025-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0004_customuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
