# Generated by Django 5.1.3 on 2025-02-26 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0005_alter_customuser_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="try_count",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="verify_code",
        ),
    ]
