# Generated by Django 5.1.3 on 2025-02-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticate", "0006_remove_customuser_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
